---
eks_clusters:
  eks_cluster_a:
    addons:
      efs:
        # amiFilter=[{"Name":"owner-id","Values":["602401143452"]},{"Name":"name","Values":["amazon-eks-node-1.20-*"]}]
        # currentImageName=unknown
        ami: "abcd"

# amiFilter=[{"Name":"owner-id","Values":["602401143452"]},{"Name":"name","Values":["amazon-eks-node-1.20-*"]}]
# currentImageName=amazon-eks-node-1.20-v20230105
ami: "ami-0ab1687f626a22bf5"
